"""Session plan schema — re-exported from OSTI (single source of truth)."""
from osti.session_plan import (  # noqa: F401
    SCHEMA_VERSION,
    ArrowType,
    BallPosition,
    DiagramInfo,
    DrillBlock,
    DrillSetup,
    EquipmentObject,
    EquipmentType,
    Extension,
    GoalInfo,
    MovementArrow,
    PageAnnotation,
    PitchView,
    PitchViewType,
    PitchZone,
    PlayerPosition,
    SessionMetadata,
    SessionPlan,
    Source,
)
